### ISSUE TITLE
Compare to previous ticker check difference (change amount)

### ISSUE THREAD

**Issue by UIApplicationMain** [hellojeffy/moneybot#3]
Compare to previous ticker check difference (change amount)

**Comment by dlee90** [comment]
What does this mean?

**Comment by UIApplicationMain** [comment]
If a stocker ticker previously requested for was re-requested, show a comparison of the change since the last request.

Ex: NFLX
-> 50$
10 minutes later
NFLX
-> 55$, +5$ (10%) since last request

**Comment by myao1** [comment]
I'm working on this now
but i'm worried about making sure it's a stable data storage. 
I'm using a dictionary which would get recreated everytime you shutdown and restart moneybot

**Comment by UIApplicationMain** [comment]
I think the dictionary is fine, it would be unavoidable to not re-create without connecting somewhere, which is over necessary

**Comment by UIApplicationMain** [comment]
Was released in earlier version.
